// Harvard Track Strength workouts — sourced from Supplemental Workouts.xlsx
// Each exercise optionally has one or more video URLs that open in a new tab.

export const STRENGTH_WORKOUTS = [
  {
    id: 'str1',
    title: 'Workout #1: Yavin',
    type: 'Full Body',
    typeBadge: 'bg-orange-100 text-orange-700',
    note: '',
    exercises: [
      { name: 'Pushups',             reps: '20 max (break up if necessary)', videos: [] },
      { name: 'Prisoner Squats',     reps: '20 max',                         videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=cpHY0nqApxg' }] },
      { name: 'V-Sits',              reps: '20 max',                         videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=DTk22KGYVsM' }] },
      { name: 'Back Hypers',         reps: '10 max',                         videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=qtjJUWCnDyE' }] },
      { name: 'Plyo Pushups',        reps: '10 max',                         videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=GR0ZL7f7u18' }] },
      { name: 'Rocket Jumps',        reps: '2 sets of 10 max',               videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=JPlK7BR1NCw' }] },
      { name: 'Dips',                reps: '2 sets of 10 max',               videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=wjUmnZH528Y' }] },
      { name: 'Cossack Extensions',  reps: '10 stretches per side (butt low, kick feet out)', videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=zIBwnvtFh9Q' }] },
      { name: 'L-Overs',             reps: '10 per side max',                videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=6HaMgb-3Idg' }] },
      { name: '6" with Scissors',    reps: '4 × 30 seconds',                 videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=-JCvFedabXU' }] },
      { name: "Wrestler's Bridge",   reps: '2 × 30 seconds',                 videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=JaV9deN4moI' }] },
      { name: 'Burpees',             reps: '10 max',                         videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=818SkLAPyKY' }] },
    ],
  },
  {
    id: 'str2',
    title: 'Workout #2: Sernpidal',
    type: 'Core & Strength',
    typeBadge: 'bg-violet-100 text-violet-700',
    note: '',
    exercises: [
      { name: 'V-Sits',                  reps: '20 max',              videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=DTk22KGYVsM' }] },
      { name: 'Back Hypers',             reps: '10 max',              videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=qtjJUWCnDyE' }] },
      { name: 'Side Ups (L & R)',        reps: '10 max per side',     videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=QvD1XLdoIc8' }] },
      { name: 'Leg Toss / Toe Touch / Hip Lifts', reps: '10 max',    videos: [
          { label: 'Video 1', url: 'https://www.youtube.com/watch?v=Dr5XaaY7xEQ' },
          { label: 'Video 2', url: 'https://www.youtube.com/watch?v=9iEI95-eZWk' },
          { label: 'Video 3', url: 'https://www.youtube.com/watch?v=iORc5cvQhJ4' },
        ]},
      { name: 'Crunches',                reps: 'Up to 50 at a time',  videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=0t4t3IpiEao' }] },
      { name: 'Side Lifts',              reps: '3 × 10 per leg',      videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=jgh6sGwtTwk' }] },
      { name: 'Back Hyper with Twist',   reps: '10 max',              videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=z3TGYE6SfBw' }] },
      { name: 'Crunches with Twist',     reps: '30 max',              videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=FgcTwxwBgWo' }] },
      { name: 'L-Overs',                 reps: '10 per side max',     videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=6HaMgb-3Idg' }] },
      { name: 'Russian Cossacks (L & R — ankle over knee)', reps: '10 max', videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=sJFd3PAzR6I' }] },
      { name: "Wrestler's Bridge",       reps: '2 × 30 seconds',      videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=JaV9deN4moI' }] },
      { name: 'Pelvic Tilt',             reps: '2 × 10',              videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=44D6Xc2Fkek' }] },
      { name: 'Pelvic Tilt — Bicycle',   reps: '2 × 10 rotations',    videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=kkW8XFsxbyY' }] },
      { name: 'Pelvic Tilt — Crunches',  reps: '2 × 10',              videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=AXa4tgGGks4' }] },
    ],
  },
  {
    id: 'str3',
    title: 'Workout #3: Blue Day',
    type: 'Daily Pre-Run',
    typeBadge: 'bg-sky-100 text-sky-700',
    note: 'Do each of these every day before running.',
    exercises: [
      { name: 'Hand Behind Head Squats', reps: '10 count',            videos: [] },
      { name: 'V-Sits',                  reps: '10 count',            videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=DTk22KGYVsM' }] },
      { name: 'Plank (any type)',         reps: '60 seconds',          videos: [] },
      { name: 'Rocket Jumps',            reps: '10 count',            videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=JPlK7BR1NCw' }] },
      { name: 'Cossack Extensions',      reps: '10 count each side',  videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=zIBwnvtFh9Q' }] },
      { name: 'L-Overs',                 reps: '5 per side',          videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=6HaMgb-3Idg' }] },
      { name: '6" Scissors',             reps: '30 seconds',          videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=-JCvFedabXU' }] },
      { name: 'Burpees',                 reps: 'Max in 30 seconds',   videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=818SkLAPyKY' }] },
      { name: 'Donkey Kicks',            reps: '10 per side',         videos: [{ label: 'Video', url: 'https://youtube.com/shorts/YoOlLusFMYU?si=MX2qxAR_ua6mCxWr' }] },
      { name: 'Fire Hydrants (rotate hip in a circle, pretend to lift knee over a cone)', reps: '5 per side', videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=YLMNZ3p7pF8' }] },
      { name: 'Glute Bridges (hold & lift leg)', reps: '10 each side', videos: [] },
      { name: 'Oil Drills',              reps: '10 each side',        videos: [] },
    ],
  },
  {
    id: 'str4',
    title: 'Workout #4: Endor',
    type: 'Legs & Power',
    typeBadge: 'bg-green-100 text-green-700',
    note: '',
    exercises: [
      { name: 'Single Leg Squat',             reps: '10 per side max',    videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=6i2nzp2mzq8' }] },
      { name: 'Toe Touches',                  reps: '2 × 10',             videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=9iEI95-eZWk' }] },
      { name: 'Pushups',                      reps: '20 max',             videos: [] },
      { name: 'Back Hypers',                  reps: '10 max',             videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=qtjJUWCnDyE' }] },
      { name: 'Yogis',                        reps: '10 max',             videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=63-ofNUgKCk' }] },
      { name: 'Side Lifts',                   reps: '3 × 10 per leg',     videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=l_U2uoePtS4' }] },
      { name: 'Lunge Good Mornings',          reps: '10 per leg max',     videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=H11zZVU5Q60' }] },
      { name: 'Wide Pushups',                 reps: '10',                 videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=m3FTgWtJsFE' }] },
      { name: 'Lunge Walks',                  reps: '10',                 videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=R_4-f8xA9mk' }] },
      { name: 'Pushup Toe Walks',             reps: '10 if you can',      videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=blF1gZB9Sko' }] },
      { name: 'Prone Hip Extensions (flex knee)', reps: '10 per leg',     videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=lFz0wn_ssxs' }] },
      { name: 'Double Leg Eagles',            reps: '5 per side',         videos: [{ label: 'Video', url: 'https://www.youtube.com/watch?v=QZjGo0Y-_2g' }] },
    ],
  },
]
